config-event:
  event-world:
    name: "Event_World"
  spleef:
    players:
      #ATTENTION: En-dessous de 2, il est probable que l'événement ne s'effectue pas comme il faut.
      min-players: 5
      max-players: 15
    spawns:
      spawn-on-join:
        x: 1000.5
        y: 100.5
        z: 1000.5
        yaw: -90
        pitch: 0
      spawn-arene:
        x: 1029.5
        y: 95.5
        z: 1000.5
        yaw: -90
        pitch: 0
    water-detection:
      y: 86
    messages:
      #Ici seront mis ulterieurement les messages custom de l'événement en lui même
  enclume:
    timer-between-waves:
      time: 10
    players:
      #ATTENTION: En-dessous de 2, il est probable que l'événement ne s'effectue pas comme il faut.
      min-players: 10
      max-players: 30
    spawns:
      spawn-on-join:
        x: 500.5
        y: 100.5
        z: 1000.5
        yaw: -90
        pitch: 0
      spawn-arene:
        x: 510
        y: 123
        z: 988
        yaw: -90
        pitch: 0
    spawning-area:
      first-point:
        x: 510
        z: 988
      second-point:
        x: 534
        z: 1012
      #COUCHE D'APPARITION DES ENCLUMES
      y: 123
    messages:
      #Ici seront mis ulterieurement les messages custom de l'événement en lui même